### ISSUE TITLE
Unable to download via npm (This is related to npm not being able to find a file)

### ISSUE THREAD

**Issue by sadilekivan** [zingchart/zingchart-vue#19]
My output

```
npm install zingchart-vue

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/zingchart/zingchart-constants.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:```

Is there anything I can do on my part? I tried to wipe my npm cache and node_modules without success. Thanks in advance!

**Comment by dannyjuergens** [comment]
Hi there,

Did you `npm install zingchart` first? I wasn't able to reproduce this problem.

**Comment by sadilekivan** [comment]
Hi,

I did, just tried uninstalling it and then reinstalling it again too, with no effect. That's a bummer, I guess I'll try to look up where I could clear some cache.

**Comment by sadilekivan** [comment]
As I probably expected, error on my end.

I recently moved to a different computer and have not yet bothered to install git. Maybe put it as a note to the install tutorial? Anyways, still very thankful for your support, can't wait to use zingchart!
