### ISSUE TITLE
Changing height is not redrawing the graph

### ISSUE THREAD

**Issue by mertgonul** [zingchart/zingchart-vue#2]
When I change width of the graph it is adjusting itself to be responsive but when I change the height it stays at same height.

<img width="728" alt="Original" src="https://user-images.githubusercontent.com/1537176/71787658-cb414200-302b-11ea-840f-f4cd2c0011ce.png">

<img width="726" alt="Not responsive" src="https://user-images.githubusercontent.com/1537176/71787663-d5fbd700-302b-11ea-93c8-6a97bd2abefc.png">

@mike-schultz

**Comment by mertgonul** [comment]
<img width="380" alt="Screen Shot 2020-01-06 at 02 30 12" src="https://user-images.githubusercontent.com/1537176/71787730-810c9080-302c-11ea-96b8-67165546d4d7.png">

That's how the chart is behaving when you change the width but changing the height is not auto-adjusting height of the graph.

**Comment by mike-schultz** [comment]
@mertgonul ZingChart itself specifically acts as divs would, having an arbitrary width and an implicit height. 

If you would like a dynamic height, I would suggest setting the zingchart-vue component's height to 100%, and controlling the overall height in it's parent container:

```
  <div style="height:200px">
    <zingchart :height="'100%'" ref="myChart" 
               :data="{type: 'line', legend: {}, series: [{values: [1,4,6,3,5,6]}]}" >
    </zingchart>
  </div>
```

**Comment by mertgonul** [comment]
> @mertgonul ZingChart itself specifically acts as divs would, having an arbitrary width and an implicit height.
> 
> If you would like a dynamic height, I would suggest setting the zingchart-vue component's height to 100%, and controlling the overall height in it's parent container:
> 
> ```
>   <div style="height:200px">
>     <zingchart :height="'100%'" ref="myChart" 
>                :data="{type: 'line', legend: {}, series: [{values: [1,4,6,3,5,6]}]}" >
>     </zingchart>
>   </div>
> ```

Thank you. Adding "height attribute" solved my problem.
