### ISSUE TITLE
Treemap

### ISSUE THREAD

**Issue by babache** [zingchart/zingchart-vue#20]
I treemap is not included ?

**Comment by lasabahebwa** [comment]
Yes, the treemap module is included. Usually, users run into an error  when they forget to include the treemap module to the vue component i.e.

import 'zingchart/modules-es6/zingchart-treemap.min.js';

In this [demo](https://drive.google.com/file/d/175KPF4hl3WFrnl8wVUZ6SDyy1iXNWEQ4/view?usp=sharing), I included the treemap module and everything works great. You might want to use it for reference. You will need to install dependencies with `npm install` and the `npm run dev` to see the app in the browser.

![ztm](https://github.com/zingchart/zingchart-vue/assets/93678483/9fc3ce45-b7a1-499d-971b-8e37e9d38341)
