### ISSUE TITLE
Chart viewall function missing

### ISSUE THREAD

**Issue by Tim020** [zingchart/zingchart-vue#21]
Hi! Unfortunately, it looks like the [`viewall` function](https://www.zingchart.com/docs/api/methods#zoom) is not defined on the Vue chart instance. 

From the console logs, I see `_vm.$refs.chart.viewall is not a function`.

**Comment by lasabahebwa** [comment]
@Tim020 `viewall` function is actually defined on the Vue chart instance. In this [demo](https://drive.google.com/file/d/1fgyzyioLuQBO0mypLGUhQbB7vprngmg6/view?usp=sharing), I managed to use the `viewall` function in a view environment and everything works great. You might want to use it for reference. You will need to install dependencies with npm install and the npm run dev to see the app in the browser.

![viewall](https://github.com/zingchart/zingchart-vue/assets/93678483/9658d173-e515-44f1-b96c-2cd650e27ef0)
![viewall](https://github.com/zingchart/zingchart-vue/assets/93678483/62b31f05-cde8-4644-9d1c-5be15e9f860a)
