### ISSUE TITLE
Array in modules throws error

### ISSUE THREAD

**Issue by dbxnr** [zingchart/zingchart-vue#23]
[The docs specify](https://github.com/zingchart/zingchart-vue#modules-string-or-array-optional) an array or string can be used as a modules parameter, although using an array throws `TypeError: e.A2A.split is not a function` whereas a string works just fine.

I'm not sure whether this is a documentation error, or bug!

**Comment by lasabahebwa** [comment]
Hello @dbxnr 
This issue has been resolved on the wrapper. If you try passing an array on the modules property, you will not run into the error again. Please use this [demo](https://drive.google.com/file/d/1xnzcPCHPnReczBtKkUvdtBh1nO0P4K9h/view?usp=sharing) for reference.

**NB**: Don't forget to install the latest version of the vue wrapper.
![vw](https://github.com/zingchart/zingchart-vue/assets/93678483/72752e39-f57d-4e20-b2d6-e9f587c8a354)
