### ISSUE TITLE
[bug] HeatMap chart Performance 

### ISSUE THREAD

**Issue by moHaHa** [zingchart/zingchart-vue#24]
scroll lag for while becaouse of heatMap rendering

**Comment by lasabahebwa** [comment]
@moHaHa Do you mind elaborating a little more about this issue? You can as well share an illustration/screen recording that we can use for reference. It might help us towards your solution.

**Comment by moHaHa** [comment]
> illustration

I left the company and the project since may 2023 , your response is too late, anyway I'll never use this again
