### ISSUE TITLE
Build for zingchart-vue is failing

### ISSUE THREAD

**Issue by lasabahebwa** [zingchart/zingchart-vue#25]
Build for zingcharts-vue has failed same with tests on the customer's end and they were wondering if the latest version of zingcharts-vue is not working. The failing build is evident on [npm](https://www.npmjs.com/package/zingchart-vue) as you can see in the attached image.
![zv](https://github.com/zingchart/zingchart-vue/assets/93678483/92bbbec4-5397-45ac-914d-3818df20ad32)

**Comment by jeanettephung** [comment]
Updated the versions of the workflow:
https://github.com/zingchart/zingchart-vue/commit/3538aba579b823400523fc7f1a53e4dccf734e62
