### ISSUE TITLE
How to add a license in a nuxt 3 application

### ISSUE THREAD

**Issue by lasabahebwa** [zingchart/zingchart-vue#26]
When I add this line:
`zingchart.BUILDCODE = ["abcdefghijklmnopqrstuvwxy"];`

I run into a "zingchart is not defined" error as shown in the attached image

[zingcharts-demo.zip](https://github.com/zingchart/zingchart-vue/files/11963461/zingcharts-demo.zip)

![l](https://github.com/zingchart/zingchart-vue/assets/93678483/13365c86-c739-4747-ba7a-43567f3330ee)

![te](https://github.com/zingchart/zingchart-vue/assets/93678483/0d7c2f97-9d08-4db9-a9b5-1ee8e400e56f)

**Comment by jeanettephung** [comment]
The `zingchart` variable is not accessible right away.
It can only be accessed right before the component is mounted.
Therefore, `zingchart` can only be accessed in `onBeforeMounted` lifecycle hook.

```
<template>
  <div>
    <client-only>
      <ZingChartVue ref="chart" :data="chartData" />
    </client-only>
  </div>
</template>

<script setup>
import { onBeforeMounted } from 'vue'
import ZingChartVue from "zingchart-vue";

const chartData = {
  type: "line",
  series: [
    {
      values: [6, 4, 3, 4, 6, 6, 4],
    },
  ],
};

onBeforeMounted(() => {
  zingchart.BUILDCODE = [
    "b41e38e003fe4724606cc6d869d396d8b3f0e68a96c781699cfa1aaca00b7d6f",
    "ASR Analytics OEM License",
  ];
});
</script>

```

**Comment by jeanettephung** [comment]
@agois83 

Should we consider creating a NuxtJS integration docs page?
There are at least two useful information required in using `zingchart-vue` in a NuxtJS application.
1. The `<client-only>` tag is required around the `<ZingChartVue>` tags
2. The `zingchart` (and probably `ZC` -- needs testing) variables can only be accessed in the `onBeforeMounted` lifecycle hook.

**Comment by agois83** [comment]
Tasked to PINT to create new NUXT JS integration page on zingchart.com

**Comment by lasabahebwa** [comment]
@agois83 the task at hand which was about adding a license in a nuxt app was resolved. We're waiting for PINT to create new NUXT JS integration page on zingchart.com so I'll close this issue.
