### ISSUE TITLE
Chart is not rendering in Nuxt 3 after globally registering the ZingChartVue component via plugins

### ISSUE THREAD

**Issue by lasabahebwa** [zingchart/zingchart-vue#27]
@jeanettephung The chart isn't rendering as you can see in the attached screenshot

[zingcharts-demo-update.zip](https://github.com/zingchart/zingchart-vue/files/11973307/zingcharts-demo-update.zip)

![lh](https://github.com/zingchart/zingchart-vue/assets/93678483/7b0a3551-cd3b-4b62-add2-0f2cace0d17c)

![nerr](https://github.com/zingchart/zingchart-vue/assets/93678483/61faba40-33f2-4732-a7ec-75c40edd5eb3)

![nc](https://github.com/zingchart/zingchart-vue/assets/93678483/e7ac9e80-4fa8-452c-984d-c7e94967a9c1)

**Comment by jeanettephung** [comment]
Globally register ZingChartVue component into NuxtJS app by registering it as a [client-side component plugin](https://stackoverflow.com/questions/72795528/how-to-use-a-vue3-componentvue-draggable-next-inside-nuxt-3-project-as-a-plugi).

`plugins/zingchart-vue.client.js`
```
import ZingChartVue from "zingchart-vue";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("ZingChartVue", ZingChartVue); 
}); 
```

**Comment by lasabahebwa** [comment]
@agois83 This was resolved so I'll close this issue.
