### ISSUE TITLE
ZingChart maps don't seem to work in vue 3 

### ISSUE THREAD

**Issue by lasabahebwa** [zingchart/zingchart-vue#28]
Please use this [demo](https://drive.google.com/file/d/13VHD5jdUiehYphwQi-OUH1K6JQKkBnMm/view?usp=sharing) for reference. I can't seem to replicate this issue in studio application meaning it's not a problem with the ZingChart library but most likely with the zingchart-vue wrapper. [Here](https://secure.helpscout.net/conversation/2245101714/10847?folderId=6869443) is the associated ticket.
![zvm](https://github.com/zingchart/zingchart-vue/assets/93678483/065465cc-8b01-4678-a190-c81c458e20cd)

**Comment by jeanettephung** [comment]
It is missing the `zingchart/es6` import.

```
import { ref } from "vue";
import 'zingchart/es6';
import ZingChartVue from "zingchart-vue";
// import chart modules used on that page
import "zingchart/modules-es6/zingchart-maps.min.js";
import "zingchart/modules-es6/zingchart-maps-usa.min.js";

```
