### ISSUE TITLE
Vue3 Failed to resolve component

### ISSUE THREAD

**Issue by dbxnr** [zingchart/zingchart-vue#29]
I upgraded Vue to v3, using 3.0.0 of zingchart-vue, and now get `Failed to resolve component: ZingChartVue`

These are the relevant lines from my local component registration:
```
import "zingchart/es6";
import "zingchart/modules-es6/zingchart-scalableyaxis.min.js";
import ZingChartVue from "zingchart-vue";
```

**Comment by dbxnr** [comment]
Narrowing this down, the version published on NPM has `zingchart-vue: "^2.0.4"` as a dependency, which in turn  was pulling in `vue: 2.7.8` as a dependency.

Slightly fixed by using this repo as a source, although encountering `Missing ref owner context` errors now.

**Comment by agois83** [comment]
Hi dbxnr,

We will look into this asap and get back to you.

**Comment by lasabahebwa** [comment]
@dbxnr I failed to replicate the error `Failed to resolve component: ZingChartVue` you mentioned above. In this [demo](https://drive.google.com/file/d/1JrCeDmQIEwyMcuxgUiAs29CQPV4aD0JE/view?usp=sharing), I'm using Vue 3, together with `"zingchart-vue": "^3.0.0"` while using local component registration and everything seems to work fine. You might want to use it for reference.

**Comment by lasabahebwa** [comment]
@dbxnr If this issue persists on your end, please share a code demo(feel free to remove any confidential information) in any JavaScript playground like jsfiddle, codepen, codesandbox etc. It might help us towards your solution.
