### ISSUE TITLE
[Bug report] zoom event not working

### ISSUE THREAD

**Issue by P4sca1** [zingchart/zingchart-vue#4]
Noticed that the zoom event does not work when trying to add it like this:
`<zingchart @zoom="myMethod">`
Manually listening to the event via `.bind` works.

Also the `README` is kinda confusing because it wraps event listeners into an `events` object instead of  the vue `methods` object.

**Comment by mike-schultz** [comment]
Hey @P4sca1 , thanks for that! Looks like the `zoom` event was being added. Cleared up the README as well!
