### ISSUE TITLE
window is not defined.

### ISSUE THREAD

**Issue by sleep9** [zingchart/zingchart-vue#5]
window is not defined error on line 101.
if(typeof(ZC)==="undefined") ...
Using component import in Nuxt.js vue website.

**Comment by damntrecky** [comment]
Hi there,

This may be an environment issue or set up issue with our wrapper. This comment alone is not enough to figure out whats going on because the library is closed source so the output is vague.

Do you have a small working example or even codesnippet of what you are trying? Codesandbox is a great place to start -> https://codesandbox.io/s/

**Comment by r4k0nb4k0n** [comment]
![image](https://user-images.githubusercontent.com/5409746/82810651-f092f780-9ec9-11ea-82dc-8f5173ae1d69.png)
I have the same problem. 
It is just fine and smooth when loading the page first time. But the error occurs when reloading the page.

I give you the codesandbox container.

https://codesandbox.io/s/busy-buck-ilcup?file=/pages/index.vue

**Comment by mike-schultz** [comment]
Hi @r4k0nb4k0n, I took a look into this and it seems like nuxt is attempting to server side render zingchart but the window object does not exist in node.js. Currently we do not support zingchart being used as-is on the server-side without a headless browser to render out the DOM.

**Comment by P4sca1** [comment]
Here is how you can use `zingchart-vue` version 2 with nuxt in ssr.

```js
if (process.client) {
    require('zingchart/es6')
  }

  export default {
    components: {
      ...(process.client ? { zingchart: require('zingchart-vue') } : {}),
    },
  }
```

**Comment by damntrecky** [comment]
@P4sca1 Thats is a great answer. I also have a solution that might work, but haven't tried yet. There is a Node.JS build output from our cdn -> https://cdn.zingchart.com/2.9.0/. You can see our github package has a `node.js` file (https://github.com/zingchart/zingchart) so you can import:

```
import 'zingchart/node`
```

You might be able to swap the imports for each version with your if statement:

```
if (process.client) {
  require('zingchart/es6')
} else {
  require('zingchart/node')
}
```

**Comment by P4sca1** [comment]
That could work and lead to pre-rendered graphs, which could be great in some circumstances.
However it is worth considering whether the rendering is better delegated to the client browser for performance reasons. Also pre-rendering does only work when the data is already available on the server and not fetched in the browser.

**Comment by damntrecky** [comment]
> That could work and lead to pre-rendered graphs, which could be great in some circumstances.
> However it is worth considering whether the rendering is better delegated to the client browser for performance reasons. 

What would these scenarios and circumstances be? In my experience the main issue comes from performance from a large chart with many datapoints or many charts (with or without many datapoints) that are offscreen.

The benefit of SSR would be to get chart dimensions and an image of the chart. You could display this image of the chart and the client/user determines when the graph renders. Whether thats on scroll of the page, or hover of the chart image. You can use the slight of hand effect by switching a picture with a chart when needed. 

I feel it is only necessary if users are being punished by charts loading and they are not interacting or seeing them on load. Especially not necessary if many users are not punished, but a couple are. All choices for you and your team to weigh out.

**Comment by P4sca1** [comment]
True. I had the impact on the server in mind, because it has to load zingchart, fetch the data and render the chart.
