### ISSUE TITLE
Interactive Maps fails in the latest versions

### ISSUE THREAD

**Issue by josechumillas** [zingchart/zingchart-vue#6]
I've only managed to get it to work on zingchart 2.8.7. 
In the lastest version fails showing the next error:

```
TypeError
Cannot read property 'push' of undefined
```

https://codesandbox.io/s/great-firefly-nuh5e
I think that this is a code error, not an implementation error... I'm right?

**Comment by mike-schultz** [comment]
Hi @josechumillas , sorry for the delay. I believe its due to the zingchart-vue wrapper embedding that specific version of zingchart. We'll work on updating the wrapper to separate the two
